<?php
error_reporting(E_ALL & ~E_DEPRECATED);
ini_set('display_errors', 0);
session_start();

require_once __DIR__ . '/../../config/database.php';
require_once __DIR__ . '/tcpdf/tcpdf.php';

$config = require __DIR__ . '/../../config/env.php';
$apiKey = $config['gemini_key'];

$type = $_GET['type'] ?? 'executive';

$db = new Database();
$conn = $db->getConnection();

// Gather all stats
$appointments = $conn->query("SELECT COUNT(*) FROM appointments")->fetchColumn();
$permitsPending = $conn->query("SELECT COUNT(*) FROM permits WHERE status = 'Pending'")->fetchColumn();
$alertsActive = $conn->query("SELECT COUNT(*) FROM alerts WHERE status = 'Active'")->fetchColumn();
$topDisease = $conn->query("SELECT disease, SUM(cases) as total FROM alerts GROUP BY disease ORDER BY total DESC LIMIT 3")->fetchAll(PDO::FETCH_ASSOC);
$violations = $conn->query("SELECT COUNT(*) FROM violations WHERE status != 'Resolved'")->fetchColumn();

$diseases = '';
foreach ($topDisease as $d) {
    $diseases .= "{$d['disease']}: {$d['total']} cases, ";
}

$prompt = "Generate a professional executive summary report for a Municipal Health & Sanitation Department. 
Stats: $appointments appointments, $permitsPending pending permits, $alertsActive active alerts, $violations unresolved violations.
Top diseases: $diseases.
Include: 1) Overview 2) Key Findings 3) Risk Assessment 4) Recommendations. Keep under 300 words.";

// Try multiple models with fallback
$models = [
    'gemini-2.5-flash',
    'gemini-2.5-flash-lite',
    'gemini-3-flash',
    'gemini-3.1-flash-lite',
    'gemini-3.5-flash',
];

$aiText = null;

foreach ($models as $model) {
    $url = "https://generativelanguage.googleapis.com/v1beta/models/{$model}:generateContent?key=$apiKey";
    
    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode(['contents' => [['parts' => [['text' => $prompt]]]]]));
    curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/json']);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_TIMEOUT, 15);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

    $response = curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($httpCode === 200) {
        $result = json_decode($response, true);
        $aiText = $result['candidates'][0]['content']['parts'][0]['text'] ?? null;
        if ($aiText) break;
    }
}

$aiText = $aiText ?? 'AI report generation is temporarily unavailable. Please try again later.';

// Generate PDF with AI content
$pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
$pdf->SetCreator('Health & Sanitation System');
$pdf->SetTitle('AI Executive Summary');
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);
$pdf->SetFont('helvetica', '', 10);
$pdf->AddPage();

$html = '<h1>AI Executive Summary</h1>';
$html .= '<p>Generated: ' . date('Y-m-d H:i:s') . '</p>';
$html .= '<hr>';
$html .= '<p>' . nl2br($aiText) . '</p>';
$html .= '<hr><p><em>Generated by AI based on real-time system data.</em></p>';

$pdf->writeHTML($html, true, false, true, false, '');
$pdf->Output('AI_Executive_Summary_' . date('Y-m-d_His') . '.pdf', 'D');